### ISSUE TITLE
Pico Plus 2 W Wifi Support

### ISSUE THREAD

**Issue by justin-luoma** [pimoroni/pimoroni-pico#1023]

**Comment by ZodiusInfuser** [comment]
The wireless build for Pico Plus 2 W can be found here: https://github.com/pimoroni/pimoroni-pico-rp2350/releases/tag/v0.0.7

**Comment by Gadgetoid** [comment]
Answered here: https://github.com/pimoroni/pimoroni-pico-rp2350/issues/17

FYI there is a box right below the title which, when creating a new GitHub issue, permits you to explain exactly what you mean so the maintainers do not have to guess. 🤦‍♂️
