### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by simonhowkins** [pimoroni/pimoroni-pico#118]
I've got a small change to one of the examples that I'd like to contribute. How do I do that?

It looks like github has a standard way to document this - see https://github.com/pimoroni/pimoroni-pico/community

**Comment by tramcrazy** [comment]
You would need to create your own branch, make the changes, and create a pull request describing the changes. Then someone will hopefully have a look at it and potentially merge it to the main repository.

**Comment by Gadgetoid** [comment]
Contributing guidelines might be a good way to address #223

Though I think the broader process of forking/editing and raising a PR might be outside the scope of such things- there must be a good existing guide for that we can link to somewhere. This might be a little dry? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
