### ISSUE TITLE
Micropython Round LCD character bug

### ISSUE THREAD

**Issue by frankdrn** [pimoroni/pimoroni-pico#145]
When using the character function in Micropython on the round LCD the characters only print in a diagonal line. It looks like a bug on line 411 of breakout_roundlcd.cpp where int x is assigned ARG_y.

The other new modules for the breakout lcd's look to have the same bug.

**Comment by frankdrn** [comment]
I've done a pull request #164 to fix character positioning on the 3 LCD breakouts - trivial I know but I'm new to github so it seems like good practice.

**Comment by Gadgetoid** [comment]
Thank you! Absolutely welcome, and a great first PR! Merged. And released!
