### ISSUE TITLE
Who wrote the sample code??? (rgb_keypad)

### ISSUE THREAD

**Issue by MikeMitterer** [pimoroni/pimoroni-pico#158]
Lately I bought a pi pico and I tried the sample code for the rgb_keypad (Python + C++)

Take this snipped from https://github.com/pimoroni/pimoroni-pico/blob/main/examples/pico_rgb_keypad/demo.cpp#L36-L47
```c++
  uint8_t button = 0;
  for(uint8_t find = 0; find < pico_keypad.NUM_PADS; find++) {
    // check if this button is pressed and no other buttons are pressed
    if(button_states & 0x01) {
      if(!(button_states & (~0x01))) {
        lit |= 1 << button;
      }
      break;
    }
    button_states >>= 1;
    button++;
  }
```
A for-loop with "find" which is never used but a variable "button" that is incremented inside of for - WHY???
Pure documentation, spaghetti code and a lot of shift operations - OMG. Please write better samples and document your code.

**Comment by Gadgetoid** [comment]
This looks like some incredibly hastily written code for production testing that somehow got swept up into this repository. It's... :cry:  beautiful.

I specially like how `last_button_states = button_states;` happens both before *and* after `button_states` is right-shifted to oblivion.

This example is presumably preserved here so we get free publicity from r/programmerhumour and thedailywtf.

**Comment by lowfatcode** [comment]
I'm sorry to say that I did. :-)

There was a lot going on for the Pico launch and you're right that some improvements can be made here, we'll give it another good look over!

**Comment by bennuttall** [comment]
Saying "Who wrote this code?", "WHY???" and "OMG" is a poor way to engage and I'd hate to be on the receiving end of such harsh criticism. Play nice, @MikeMitterer. Respectfully, a community member who this sometimes happens to.

**Comment by lowfatcode** [comment]
To be clear I can see @bennuttall 's point and definitely consider it the correct way to approach an issue report like this.

However, since I know the context in which this code was written (16 hour days for weeks on end...) it's like water off a ducks back - I'm not offended ;-D We'll get it fixed up, thanks for pointing it out!

**Comment by Gadgetoid** [comment]
I rewrote that entire snippet to:

```c++
lit_buttons |= pico_keypad.get_button_states();
```

Doesn't have the femtoseconds of debounce that the extra instructions added, but I feel it captures the gist of it.

**Comment by Gadgetoid** [comment]
@bennuttall this you?
![image](https://user-images.githubusercontent.com/1746967/119373648-8b2a4000-bcb0-11eb-8544-53326e8b3f86.png)
