### ISSUE TITLE
Pico Wireless Pack : cannot find network

### ISSUE THREAD

**Issue by bryht** [pimoroni/pimoroni-pico#210]
I bought this module
![image](https://user-images.githubusercontent.com/2418508/135771443-1f0251cb-bf8b-4506-8b90-682ee808918d.png)

attach them like this:
![image](https://user-images.githubusercontent.com/2418508/135771504-0d2df85a-1542-40b7-a399-a365619d0a79.png)
![image](https://user-images.githubusercontent.com/2418508/135771508-57da8790-4d23-4f40-a9ef-85f9eafdc423.png)

and flash the uf2 with newest version: https://github.com/pimoroni/pimoroni-pico/releases/tag/v0.2.6

but when I try the example code : https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/pico_wireless/cheerlights.py

it cannot get wifi connect, always return status 255, rather than 3.
then I tried get all the networks it returns 0.

![image](https://user-images.githubusercontent.com/2418508/135771414-54f2d5d5-0ad7-49f8-b2d3-a6cd0b8eb0db.png)
![image](https://user-images.githubusercontent.com/2418508/135771587-cf85eee2-8952-4a41-b0aa-5532c8b516af.png)

Anyone may knows what the problem is? thanks in advance.

**Comment by Gadgetoid** [comment]
This *could* be a soldering/electrical issue but I'm not sure how. I've run a couple of tests locally and I can list networks.

Might be worth noting that it finds only 2.4GHz networks and not 5GHz ones, so if your area somehow doesn't have any 2.4GHz networks that might also explain the lack of them.

**Comment by bryht** [comment]
> This _could_ be a soldering/electrical issue but I'm not sure how. I've run a couple of tests locally and I can list networks.
> 
> Might be worth noting that it finds only 2.4GHz networks and not 5GHz ones, so if your area somehow doesn't have any 2.4GHz networks that might also explain the lack of them.

Hi Gadgetoid, thanks for the quick response, I double checked, I have 2.4Hz networks, really don`t know if it is an electrical issue, but when I run the code, the light has a strange color, seems blue,red,green together, do you know if that indicate something?
![image](https://user-images.githubusercontent.com/2418508/135922186-242be54c-e1ce-4e3d-b9b1-1a961f104547.png)

**Comment by Gadgetoid** [comment]
It's fairly normal for the LED to just sort-of do its own thing when it's not being actively driven to a known state.

Could you take some photos of the Pico header soldering? From your side-on photo some of the joints look a little dry, but it's hard to tell. The solder should ideally form a little cone, covering the copper ring around each pin, rather than a bulge at the end of the pin.

**Comment by bryht** [comment]
Hi Gadgetoid, that is quick 👍 

here are the Pico side, do you mean by this? can you tell any issue? actually I didn`t solder them, it is like this when I bought it.
![image](https://user-images.githubusercontent.com/2418508/135926162-9321ef61-7e23-40d9-a89e-89a205c39791.png)
![image](https://user-images.githubusercontent.com/2418508/135926178-a5d2626f-bf65-487a-b03f-81cfa13d78e5.png)

**Comment by bryht** [comment]
> It's fairly normal for the LED to just sort-of do its own thing when it's not being actively driven to a known state.
> 
> Could you take some photos of the Pico header soldering? From your side-on photo some of the joints look a little dry, but it's hard to tell. The solder should ideally form a little cone, covering the copper ring around each pin, rather than a bulge at the end of the pin.

Hi Gadgetoid, that is quick 👍

here are the Pico side, do you mean by this? can you tell any issue? actually I didn`t solder them, it is like this when I bought it.
![image](https://user-images.githubusercontent.com/2418508/135926706-827b9c97-6f7c-45d2-be93-6e82eb892b85.png)
![image](https://user-images.githubusercontent.com/2418508/135926736-ac2cfa13-6863-491b-ae7b-f5d416645fce.png)

**Comment by Gadgetoid** [comment]
Ah! The header looks fine. It was just the shallow angle in the first picture that made it look funny.

Might be worth also firmly pressing the Pico and Pico Wireless together to make sure they're connected- though it seems like they are communicating at least.

I'm not sure what else could be wrong. 🤔

**Comment by Gadgetoid** [comment]
Have run this by support, you should drop an email to support@pimoroni.com since they'd be able to replace it if it's a hardware fault.
