### ISSUE TITLE
Plasma 2040 UART RX TX Possible?

### ISSUE THREAD

**Issue by xarnze** [pimoroni/pimoroni-pico#216]
Does anyone know if it's possible to connect to the UART pins on the pico with this board?

**Comment by tigerteeth** [comment]
I'm getting an error on this:

uart = UART(0, baudrate=9600, tx=Pin(20), rx=Pin(21), timeout=1)

>>> %Run -c $EDITOR_CONTENT
MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
ValueError: bad TX pin
>>>
