### ISSUE TITLE
Build-Instructions for building firmware myself, missing ?

### ISSUE THREAD

**Issue by jogi-k** [pimoroni/pimoroni-pico#223]
I am looking for a way to create the firmware myself.
I couldn't find anything.
Are there anywhere hints on how to do this?

**Comment by Gadgetoid** [comment]
The steps are pretty explicitly laid out by the GitHub workflow that builds our releases/test builds: https://github.com/pimoroni/pimoroni-pico/blob/v0.3.3/.github/workflows/micropython.yml

Some documentation effort wouldn't go amiss though, I could have sworn I wrote it down *somewhere*.
