### ISSUE TITLE
Release 0.3.1 with Blinka seems to be missing the picokeypad module

### ISSUE THREAD

**Issue by dannystaple** [pimoroni/pimoroni-pico#224]
In the Pimoroni Pico release 0.3.1 with pimoroni libs only, I am able to import picokeypad.
In release 0.3.1, with Pimoroni Libs + Adafruit Blinka + Adafruit PlatformDetect I am unable to - the module isn't found.

**Comment by helgibbons** [comment]
I've just tried this with 0.3.1 + Blinka + PlatformDetect and `import picokeypad` seems to be behaving itself for me - can you let us know the exact error you're getting and what code are you trying to run?

**Comment by dannystaple** [comment]
I can't reproduce this. Something really odd going on here. Going to close it - maybe I put the non-pimoroni Micropython on by mistake?
