### ISSUE TITLE
Documentation: pico_rgb_keypad, Readme.md, get_button_states

### ISSUE THREAD

**Issue by wwoofbum** [pimoroni/pimoroni-pico#229]
changed_buttons = current_buttons ^ last_buttons
...
pressed_buttons = current_buttons & changed

- should read -

pressed_buttons = current_buttons & **changed_buttons**
...
released_buttons =  last_buttons & changed

- should read -

released_buttons =  last_buttons & **changed_buttons**

**Comment by Gadgetoid** [comment]
Fix inbound. Good catch, thank you!
