### ISSUE TITLE
RTC for Interstate75

### ISSUE THREAD

**Issue by carlskii** [pimoroni/pimoroni-pico#230]
Hi, I've been playing with the new interstate75 board. However, I notice it doesn't include an RTC which makes the clock examples somewhat limited unless its tethered to a computer. Do you have a recommend RTC for interstate75 and maybe an example on how to use it ?

**Comment by Gadgetoid** [comment]
The RP2040 already has an RTC built-in. See: https://github.com/raspberrypi/pico-examples/blob/master/rtc/hello_rtc/hello_rtc.c

**Comment by carlskii** [comment]
Thanks - so how would I get interstate75 to retrieve/maintain the correct time after it's booted ?

**Comment by Gadgetoid** [comment]
My uh... unothadox solution was - albeit using MicroPython (where it's done automagically) - to allow the time to be set via a host computer, then use a battery to relocate the panel while powered on.

The time will be saved in the RTC during a power-off, but wont advance, so a quick swap to battery works quite well. Granted this isn't very robust!

If you want the RTC to keep ticking during a loss of power (or while powered down) you'd have to use something like the RV3028 with a little coin cell backup - https://shop.pimoroni.com/products/rv3028-real-time-clock-rtc-breakout wired using our Qw'st adapters and cables like so:

![image](https://user-images.githubusercontent.com/1746967/146543352-1ea3b131-a8f9-4a2d-876b-829d0eb21968.png)

https://shop.pimoroni.com/products/stemma-qt-qwiic-to-breakout-garden-adapter
https://shop.pimoroni.com/products/jst-sh-cable-qwiic-stemma-qt-compatible?variant=31910609813587

Or add some controls to make manually setting the time in the built-in RTC easier- granted that'll lose time when power is lost.

**Comment by ZodiusInfuser** [comment]
Closing this as it appears the question was answered. If it was not, please reopen.
