### ISSUE TITLE
Badger2040/Badge.py Fails reading image file + fix

### ISSUE THREAD

**Issue by erawretsila** [pimoroni/pimoroni-pico#253]
I think this must have been a simple one that silpped through the net n testing
Line 37:
    open("Raspberry.bin", "rb").read_into(BADGE_IMAGE)

AttributeError: 'FileIO' object has no attribute 'read_into'

should be
    open("Raspberry.bin", "rb").readinto(BADGE_IMAGE)

**Comment by Gadgetoid** [comment]
Yup, thank you, fix merged here - https://github.com/pimoroni/pimoroni-pico/pull/254

If you're using the badge.py baked into the firmware, I'll put together a new firmware release towards the end of the week, to hopefully give time to catch other issues and make some tweaks.

Pre-release build can be found here - https://github.com/pimoroni/pimoroni-pico/suites/5489822653/artifacts/175367214
