### ISSUE TITLE
Badger2040 - Broken link or missing file

### ISSUE THREAD

**Issue by thagrol** [pimoroni/pimoroni-pico#258]
The link from https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/modules/badger2040 to https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/badger2040/examples/badger2040/image_converter results in a 404 error.

**Comment by Gadgetoid** [comment]
My bad, got my wires crossed with relative repo links. It's here - https://github.com/pimoroni/pimoroni-pico/tree/main/examples/badger2040/image_converter
