### ISSUE TITLE
Badger 2040 - AttributeError: 'badger2040' object has no attribute 'invert'

### ISSUE THREAD

**Issue by niko86** [pimoroni/pimoroni-pico#261]
I'm currently running bootloader:

- MicroPython v1.18-128-g2ea21abae-dirty on 2022-02-24; Pimoroni Badger 2040 2MB with RP2040

When I try to invert an image I get an attribute error as follows:

- AttributeError: 'badger2040' object has no attribute 'invert'

**Comment by helgibbons** [comment]
Try updating to the latest version of Badger flavoured MicroPython from the [releases page](https://github.com/pimoroni/pimoroni-pico/releases)! I think invert was a recent addition to the firmware.

**Comment by helgibbons** [comment]
Closing for now but let us know if you're still stuck!
