### ISSUE TITLE
Badger 2040 - ImportError: no module named 'launchericons'

### ISSUE THREAD

**Issue by gnuchu** [pimoroni/pimoroni-pico#262]
When trying to run launcher.py from the badger examples it tries to do an import of a module 'launchericons' that doesn't seem to exist anywhere not in this repo, not on pypi.

**Comment by Gadgetoid** [comment]
Are you using the Badger2040 version of MicroPython? It’s a built-in module.

Linked here - https://github.com/pimoroni/pimoroni-pico/releases/tag/1.18.2

**Comment by gnuchu** [comment]
Ah nice one thanks. I'd grabbed the wrong firmware.
