### ISSUE TITLE
badger2040: demo and micropython are not mountable

### ISSUE THREAD

**Issue by remotelink** [pimoroni/pimoroni-pico#282]
hi to all!
my new badge does not offer a mountable usb-flash-drive. 
- linux see the badge **lsusb** 
- offer a working **/dev/ttyACM0** serial-usb interface
- but no mountable flash drive when using the **DEMO** 
- no mountable flash dirve when using **micropython*.u2f**

while flashing the circuit-python*.u2f the flash-drive works as expected. main.py resp. code.py are accessable.

... any ideas what could be wrong with this?
tnx remotelink

**Comment by helgibbons** [comment]
Once you've installed MicroPython, Badger won't show up as a drive on your computer. You'll need to program it with an interpreter such as Thonny.

Check out https://learn.pimoroni.com/article/getting-started-with-badger-2040 !

**Comment by shbisson** [comment]
I've been doing this, but there do seem to be some differences between the article and my device. For example, in the badge applet I can stop the code and edit the text, but I can't see the /images directory to upload a new image. I've tried from Thonny on Windows, on Mac, and on a Pi400.

**Comment by helgibbons** [comment]
@shbisson `/images` is created the first time you run `image.py`.

Your `badge-image.bin` shouldn't be in there though, it needs to be in the root directory - check out the section of the [tutorial](https://learn.pimoroni.com/article/getting-started-with-badger-2040) relating to `badge.py`!

Make sure you're running the [most recent version of Badger MicroPython](https://github.com/pimoroni/pimoroni-pico/releases/) (1.18.3) too - I think there was a bug that affected the badge example in 1.18.2.

**Comment by shbisson** [comment]
Gotcha! I have an image now showing, but it's not parsed correctly by the badge app. I shall experiment with conversions. Thanks.
