### ISSUE TITLE
Badger 2040 - Click button trigger GPIO

### ISSUE THREAD

**Issue by thalesfsp** [pimoroni/pimoroni-pico#295]
I would like to to connect the Badger 2040 to my RPI. Basic idea: Clicking in some Badger 2040 button would trigger an action in the RPI. Is this possible?

**Comment by Gadgetoid** [comment]
Using MicroPython I'd hook it up via USB and do this over serial using Python/pyserial - https://pyserial.readthedocs.io/en/latest/pyserial_api.html

You then just need to make pressing a button print something, watch for that over serial and act accordingly.

CircuitPython could pretend to be a keyboard and send whole USB HID macros, but how useful those are depends on what you want to achieve.

**Comment by thalesfsp** [comment]
I was thinking over GPIO, not serial as a keyboard.

**Comment by thalesfsp** [comment]
@Gadgetoid Would be possible to connect the badger to a stepper motor driver (GPIO)?

**Comment by ZodiusInfuser** [comment]
Closing this as it looks like the original question was answered, and the follow-up question was raised and answered separately https://github.com/pimoroni/pimoroni-pico/issues/323
