### ISSUE TITLE
qrcode as .py file from Badger 2040

### ISSUE THREAD

**Issue by niko86** [pimoroni/pimoroni-pico#300]
Apologies if this is not the place for such a request. 

I am looking to use the qrcode on an inky e-ink display using a pico and the qrcode library works great on my badger. Compiling my own micropython with qrcode in it is way beyond my skills and I can only see a c file of the code in this repository. Is there a python version of the file or is this not possible? Or is there a way to use the uncompiled c code on my pico?

Thanks

**Comment by Gadgetoid** [comment]
The QRCode library is baked into our custom MicroPython build, grab it here- https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.18.4

Or - direct .uf2 link for a 2MB stock Pico board - https://github.com/pimoroni/pimoroni-pico/releases/download/v1.18.4/pimoroni-pico-v1.18.4-micropython.uf2
