### ISSUE TITLE
MicroPython: Merge PAA5100 and PMW3901 into a single module

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/pimoroni-pico#301]
These bindings are functionally identical. They could be merged into a single set of bindings with two module aliases to save some storage and make maintenance easier. I don't think they are likely to diverge?

**Comment by ZodiusInfuser** [comment]
Erm... I thought both sensors had different secret source in addition to the physical lens difference? See:
https://github.com/pimoroni/pimoroni-pico/blob/ba5cffdb0d9de8cc60f84b4c6dc2ddbe31db5871/drivers/pmw3901/pmw3901.cpp#L282
and
https://github.com/pimoroni/pimoroni-pico/blob/ba5cffdb0d9de8cc60f84b4c6dc2ddbe31db5871/drivers/pmw3901/pmw3901.cpp#L427

So the switch to only calling this constructor would only have the PWM3901's sauce applied when init is called
https://github.com/pimoroni/pimoroni-pico/blob/887ae3d37372d97e93b408b5709c22a98792c953/micropython/modules/breakout_pmw3901/breakout_pmw3901.cpp#L135

**Comment by Gadgetoid** [comment]
Good catch, I've updated the code to take this into account, testing a fair bit, and merged! :grimacing:
