### ISSUE TITLE
Invalid mode for reading

### ISSUE THREAD

**Issue by goldstar611** [pimoroni/pimoroni-pico#307]
If the text file is not found, it is created but then after the except block a read is attempted. This is invalid for the `w` mode and should be changed to either `r+` or `w+` to avoid another error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
io.UnsupportedOperation: not readable
```

https://github.com/pimoroni/pimoroni-pico/blob/fa2774b1147257e537e91c29f4ee270459d2b2e4/micropython/examples/badger2040/badge.py#L184

**Comment by Gadgetoid** [comment]
I snuck a fix for this into 1.18.5.
