### ISSUE TITLE
Badger QR, info and help apps exit on any button press

### ISSUE THREAD

**Issue by MichaelBell** [pimoroni/pimoroni-pico#317]
Apps that just call `halt()` and exit will quit to launcher when any button is pressed.  They should halt in a loop instead.

**Comment by Gadgetoid** [comment]
Ah, here was me thinking halt was blocking but I must have got confused!

**Comment by MichaelBell** [comment]
Halt blocks until any front button is pressed, but we should only exit if A+C are pressed together.
