### ISSUE TITLE
Badger 2040 list app: long entries overlap next entry

### ISSUE THREAD

**Issue by PieterJanSterk** [pimoroni/pimoroni-pico#320]
Hi, code seems to imply that the text should be scale accordingly. This does not seem the case however? When I add a long(er) line to the checklist.txt file, the next entry is overwritten on the Badger.

**Comment by Gadgetoid** [comment]
It currently doesn't do anything fancy, but perhaps could do. Marked as enhancement for when I get a moment to look into it.

**Comment by Gadgetoid** [comment]
Badger 2040 and Badger 2040 W now live here: https://github.com/pimoroni/badger2040/

Closing this issue to keep Badger 2040 to its new home. Please feel free to re-open over at https://github.com/pimoroni/badger2040/issues with a link back here for posterity.
