### ISSUE TITLE
After upgrading to latest release, Thonny doesn't work anymore (Badger 2040)

### ISSUE THREAD

**Issue by thalesfsp** [pimoroni/pimoroni-pico#321]
1. Copied [pimoroni-badger2040-v1.18.5-micropython.uf2](https://github.com/pimoroni/pimoroni-pico/releases/download/v1.18.5/pimoroni-badger2040-v1.18.5-micropython.uf2) file to Badger 2040
2. Open Thonny:
```
Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - use Stop/Restart to interrupt more and enter REPL.
```

If I copy [pimoroni-pico-v1.18.5-micropython.uf2](https://github.com/pimoroni/pimoroni-pico/releases/download/v1.18.5/pimoroni-pico-v1.18.5-micropython.uf2), it works.

**Comment by helgibbons** [comment]
Is this when you press stop in Thonny? If so, try pressing reset on the board and then stop?

Adding the battery saving stuff meant changes to most of the examples, so if you have older versions of the examples around that might be stopping the new release from working properly. You can clearing the flash memory using the method described in the [tutorial](https://learn.pimoroni.com/article/getting-started-with-badger-2040):

> HOW DO I FACTORY RESET?
> If you need to delete all your programs from Badger's flash memory and start again from scratch, you can do that by downloading [this special .uf2 file](https://www.raspberrypi.org/documentation/pico/getting-started/static/6f6f31460c258138bd33cc96ddd76b91/flash_nuke.uf2) and copying it to your Badger whilst it's in bootloader mode. Once you've done that, you'll need to copy the Badger MicroPython image across again.
> 
> You may also find clearing the flash to be useful if you encounter problems after upgrading to the newest version of MicroPython - just make sure you save any code you've been working on to your computer first!

**Comment by thalesfsp** [comment]
Thank you!
