### ISSUE TITLE
Badger 2040 and Serial Comms

### ISSUE THREAD

**Issue by hammarbytp** [pimoroni/pimoroni-pico#331]
Would there be anyway to talk to the Badger via RS232, either natively ot through an adapter?

**Comment by Gadgetoid** [comment]
There are UART TX/RX pins broken out along the edge of Badger, these aren't configured to do anything in MicroPython but are typically used with stdio in C++ programs- so when you "printf" it's implicitly routed over serial. Either way you can grab these pins and send/receive whatever you like over them.

If you want to use an RS232 port with this you'll need some logic level conversion. IE: An RS232 to TTL converter with 3.3v logic levels.

**Comment by ZodiusInfuser** [comment]
Closing this as it appears the question was answered. If it was not, please reopen.
