### ISSUE TITLE
Pico Display - enhance functions

### ISSUE THREAD

**Issue by nickwebcouk** [pimoroni/pimoroni-pico#34]
Is there a road map for what functions you'll be adding to the Pico Display? I'd like to put my 2p worth in - could it be possible in MicroPython to get the length of a string in pixels so that based on that we can work out where to place it on the screen? (i.e for centring on the screen or in shapes we have created?

Also is there a better place for code addition suggestions?

**Comment by Gadgetoid** [comment]
I believe @lowfatcode is putting together  some very nice text rendering functions including basic Markdown rendering support. Would be best to wait for these to roll along before tackling anything.

Measuring text might well be part of his change set! It’s a useful tool to have.
