### ISSUE TITLE
Micropython bindings: LCD breakout - line and triangle drawing primitives fail silently

### ISSUE THREAD

**Issue by cedel1** [pimoroni/pimoroni-pico#343]
When using 'display.line' and 'display.triangle' micropython methods, these fail silently (nothing get drawn on the display), while 'display.circle' works. Tested with 'BreakoutRoundLCD' class and round LCD.

**current behavior:** using 'line' and 'triangle' methods renders nothing on the display
**expected behavior:** line and/or triangle gets drawn in the display (depending on the method used)

**Comment by cedel1** [comment]
I have digged into the issue a little and the result is the following pull request:

https://github.com/pimoroni/pimoroni-pico/pull/344

A few unrelated notes:
- there may be different ordering of R, G, B channels for the different micropython classes for the various displays (or it's a C/C++ or hardware difference) - cannot check that as I don't have the rectangular LCDs.
- the error seems simple enough to fix, tests should (if they existed) have discovered the problem much sooner.

**Comment by cedel1** [comment]
Fixed in _main_ branch by merging https://github.com/pimoroni/pimoroni-pico/pull/344 .

**Comment by helgibbons** [comment]
Closing as I think this is now merged in and sorted - yell if not :)
