### ISSUE TITLE
Trying to use convert.py to create icons to display on launcher instead but get a black square

### ISSUE THREAD

**Issue by Phyore** [pimoroni/pimoroni-pico#356]
```
import os
    try:
        ICONS = [f for f in os.listdir("/icons") if f.endswith(".bin")]
    except OSError:
        pass
    
    
    for i in range(max_icons):
        x = centers[i]
        label, icon = examples[i + (state["page"] * 3)]
        label = label[1:].replace("_", " ")
        display.pen(0)
        
        
        # My stuff
        file = label+'.bin'
        name = file.split(".")[0]
        
        icon = bytearray(int(64 * 64 / 8))
        try:
            open("icons/"+file, "r").readinto(icon)
            print(icon)
        except OSError:
            pass
        
        display.image(icon, 64, 64, x - 32, 24)
```

Trying to use the above to pull out the icons created with convert.py using the below command in Thonny. However the image displays as a simple black square in the launcher above help. 
`%Run convert.py --binary help.png`
![help](https://user-images.githubusercontent.com/2222368/168310896-03591be0-c75a-40ca-9bfd-264ef5efe02b.png)

I am not very familiar with Python at all so I have been trying to make do with snipping functions and code from various other places (The above was from the image viewer). I however did get a version of the image working from a friend who helped me by creating the bin file in a different program.

**Comment by North101** [comment]
It's probably because the icon has transparency and the converter converts it to black. Try adding a white background to the icon
