### ISSUE TITLE
Need halt with timeout

### ISSUE THREAD

**Issue by aaronw2** [pimoroni/pimoroni-pico#367]
It would be very useful to have a halt with timeout. In my badge code I want it to wake up when either a button is pressed or when a timeout happens so that I can have a clock on my badge. The code I am writing allows me to switch between multiple badges but I also thought it would be nice to display the date and time as well. I don't want to drain the battery constantly polling.

**Comment by Gadgetoid** [comment]
As soon as you call "halt" the Badger is off, power is cut, there's no way to implement a timeout I'm afraid.
