### ISSUE TITLE
Pimoroni Lipo Pico UF2 v1.19.0 Examples

### ISSUE THREAD

**Issue by socratesv** [pimoroni/pimoroni-pico#396]
The GitHub link: https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules/picographics/README.md takes you to a page of Display examples, one of which has an error regarding the rotate function, specifically:

Supported Rotations
All SPI LCDs support 0, 90, 180 and 270 degree rotations.

Eg:

display = PicoGraphics(display=PICO_DISPLAY, roation=90)

The example has a spelling error and the correct way is (thank you alphanumeric007 for helping me out on this)

display = PicoGraphics(display=PICO_DISPLAY, rotate=90)

Can someone please fix this?  

many thanks.

**Comment by Gadgetoid** [comment]
Fixed by https://github.com/pimoroni/pimoroni-pico/pull/395 I think
