### ISSUE TITLE
badger_os.launch resetting the badge.

### ISSUE THREAD

**Issue by JPBarroso** [pimoroni/pimoroni-pico#403]
I've added a modified badge.py and a new badge2.py files that can launch each other. What I'm using is:
`if display.pressed(badger2040.BUTTON_A):
        badger_os.launch("badge2")`
Now, from the modified badge.py, it'll launch badge2 no problem regardless of how I'm running the script - either from Thonny or from the launcher.
BUT, from badge2.py it'll launch _badge_ **only** when running the script via Thonny - if I launch badge.py from the launcher, the badger2040 will reboot itself and kick me to the launcher.

**Comment by Gadgetoid** [comment]
Badger 2040 and Badger 2040 W now live here: https://github.com/pimoroni/badger2040/

The upgraded Badger OS stuff might have fixed this issue, or at least changed things significantly to change its dynamic.

If not please feel free to re-open over at https://github.com/pimoroni/badger2040/issues with a link back here for posterity.
