### ISSUE TITLE
Pico W requires a different binary file than original Pico, is there Pimoroni micropython Uf2 for the Pico W?

### ISSUE THREAD

**Issue by lesley-byte** [pimoroni/pimoroni-pico#425]
Does anyone have a Pimoroni flavor Micropython Uf2 for the Pico W?  I know from reading the documentation that the binary files have to be different for each board.  I suspect it might still be in development but wanted to know if there was anything out there yet.

**Comment by alphanumeric007** [comment]
You could try this one, its an unofficial build, just so you know.
[https://github.com/pimoroni/pimoroni-pico/actions/runs/2594804454 ](url)

**Comment by digitalurban** [comment]
Does this have the wifi modules ?

**Comment by Gadgetoid** [comment]
I've just tagged a 1.19.1 pre-release that includes support for Pico W - https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.19.1

Modules for connecting to wireless are included, but you'll need to install various stdlib libraries to do anything useful. I've put together some examples for Pico Inky that might help - https://github.com/pimoroni/pimoroni-pico/pull/420/files

**Comment by lesley-byte** [comment]
done.  Thank you
