### ISSUE TITLE
example file clock.py burns ghost image into inky pack

### ISSUE THREAD

**Issue by lesley-byte** [pimoroni/pimoroni-pico#432]
Clock.py works but it seems to burn a ghost of itself (I left it on for 10 minutes) that shows when you refresh to a different program.  It's not horrible but I'm wondering if updating every second is really a good goal for inky pack.   it might be better to just indicate the hour and minute or just the day of the week and the date.  Just to avoid the ghost forming as quickly.

**Comment by helgibbons** [comment]
We wouldn't recommend running clock.py as is for long periods of time, but it works rather nicely as a demo of Badger's turbo updates (and the downsides of using fast updates - i.e. ghosting!). If you fancy submitting a PR for a more update friendly clock, we'd be very happy to take a look at it :)

Closing for now.
