### ISSUE TITLE
v1.19.5 Pico W uf2 firmware is missing urequests

### ISSUE THREAD

**Issue by TheLogster** [pimoroni/pimoroni-pico#472]
The following code works on a stock Rasberry pico w firmware, but on v.1.19.5 pimoroni pico w firmare (pimoroni-picow-v1.19.5-micropython.uf2) an import error occurs:

`import network`
`import secrets`
`import time`
`import urequests`
`wlan = network.WLAN(network.STA_IF)`
`wlan.active(True)`
`wlan.connect(secrets.SSID, secrets.PASSWORD)`
`print(wlan.isconnected())`
`astronauts = urequests.get("http://api.open-notify.org/astros.json").json()`
`number = astronauts['number']`
`for i in range(number):`
    `print(astronauts['people'][i]['name'])`
    
    
`Traceback (most recent call last):`
  `Fle "<stdin>", line 4, in <module>`
`ImportError: no module named 'urequests'`

**Comment by Gadgetoid** [comment]
Hmm, I see why. Let me see if I can fix that.

**Comment by Gadgetoid** [comment]
This build should include it, and it'll be in the next release shortly! - https://github.com/pimoroni/pimoroni-pico/actions/runs/2745701291

**Comment by TheLogster** [comment]
Thanks :)
