### ISSUE TITLE
urequests module in the pico w uf2

### ISSUE THREAD

**Issue by bitcoina** [pimoroni/pimoroni-pico#475]
I'm not a techie, so please feel free to correct me if I'm missing something obvious. 

I've got a unicorn for my pico w, and want to use it to display the output of an api call.   (which is obtained using urequests module). 

However the pimoroni uf2 doesn't seem to include the urequests module, while the raspberry pi uf2 includes it.

Is this something that can be easily included?

**Comment by Gadgetoid** [comment]
urequests should be in 1.19.6 - https://github.com/pimoroni/pimoroni-pico/releases

**Comment by bitcoina** [comment]
Great, it works now!  Many Thanks!
