### ISSUE TITLE
Badger 2040 got stuck with the latest firmware v1.19.6 

### ISSUE THREAD

**Issue by arturi** [pimoroni/pimoroni-pico#484]
I upgraded to `pimoroni-badger2040-v1.19.6-micropython.uf2` and it acts like the OS is not there — I can program the screen and LED, but the OS never comes up. Downgrading to `v1.19.5` seems to have solved the issue. Could it be that it’s the wrong file in the firmware, the one without the Badger OS?

**Comment by alphanumeric007** [comment]
There are two custom uf2 files for the badger. One with badger OS and one without. ;)

**Comment by Gadgetoid** [comment]
:thinking: I hope I haven't accidentally excluded the OS from *both* somehow :grimacing:

**Comment by Gadgetoid** [comment]
Raised a fix for this in #485 -

You can try a test build from here: https://github.com/pimoroni/pimoroni-pico/actions/runs/2796019412

**Comment by sctv** [comment]
Tried #485, it works! Thanks.

**Comment by sctv** [comment]
[artefact](https://github.com/pimoroni/pimoroni-pico/suites/7663615190/artifacts/319388266)
