### ISSUE TITLE
Pico Explorer - missing modules / old code

### ISSUE THREAD

**Issue by RedDogUK** [pimoroni/pimoroni-pico#499]
A number of the demo scripts (e.g. [button_test.py](https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/pico_explorer/button_test.py)) is failing to run due to an import error message:  no module named 'picoexplorer'.  please either update the picow libruary (I used [v1.19.6](https://github.com/pimoroni/pimoroni-pico/releases/download/v1.19.6/pimoroni-picow-v1.19.6-micropython.uf2)) or update the demo scripts.

**Comment by helgibbons** [comment]
As luck would have it, I addressed this yesterday with #498 :) 

Until it's merged in, you can find updated examples and docs at the links below:
- https://github.com/pimoroni/pimoroni-pico/tree/purge-picoexplorer/micropython/examples/pico_explorer
- https://github.com/pimoroni/pimoroni-pico/tree/purge-picoexplorer/micropython/modules/pico_explorer
