### ISSUE TITLE
picow Version 1.19.7 file extensions

### ISSUE THREAD

**Issue by RedDogUK** [pimoroni/pimoroni-pico#501]
Once the ufs files were unpacked onto the Pico W, some fo the file extensions were listed as .mpy and were not able to be read.

**Comment by helgibbons** [comment]
As I understand it, .mpy files are Python scripts compiled into a compressed binary format to save RAM, you won't be able to open/edit them with Thonny. 

Are you referring to the files in micropython/examples/common ? There's links to the .py versions here: https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/common

**Comment by helgibbons** [comment]
Closing for now, but let us know if you're still having issues!
