### ISSUE TITLE
What image incorporate the badger2040 module - RESOLVED

### ISSUE THREAD

**Issue by ph1lj-6321** [pimoroni/pimoroni-pico#502]
Hi
Please let me know what MicroPython image features the badger2040 module, I'm simply trying to test the 'button_test.py' script in Thonny.

I've tried the 1.19.7 2022-08-10 - comes back with no module named 'badger2040'

**Seems to be in 1.19.6 2022-07-27**

**Comment by helgibbons** [comment]
Sounds like you're sorted - closing for now!

If anyone else stumbles across this issue, the most recent Badger image is [pimoroni-badger2040-1.19.7-micropython.uf2](https://github.com/pimoroni/pimoroni-pico/releases/download/1.19.7/pimoroni-badger2040-1.19.7-micropython.uf2)
