### ISSUE TITLE
BME280 example displays ER when result is read fine

### ISSUE THREAD

**Issue by johnvanham** [pimoroni/pimoroni-pico#504]
Hello, I think this looks like a bug? Or have I misunderstood.

The example for the BME280 loads a reading from the board in forced mode but then the output checks whether results.status == BME280_OK

BME280_OK is set in the driver as 0

Yet status is a boolean set by the read_forced() function. So it prints ERR because 0 = false when actually it is OK?

https://github.com/pimoroni/pimoroni-pico/blob/05ef0d7f037ad5050d8612d23c9829e0e6f29204/examples/breakout_bme280/bme280_basic.cpp#L25-L26

https://github.com/pimoroni/pimoroni-pico/blob/05ef0d7f037ad5050d8612d23c9829e0e6f29204/drivers/bme280/bme280.cpp#L59

**Comment by thirdr** [comment]
This has now been fixed in #943
