### ISSUE TITLE
Where is `WIFI_CONFIG`

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pimoroni/pimoroni-pico#513]
I don't understand how to import and edit `WIFI_CONFIG` which is used almost everywhere. Could you please post a link to where download it?

Thanks!

**Comment by helgibbons** [comment]
You can find it in [micropython/examples/common](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/common)

There should be some instructions on what to do with the common files in the relevant examples readme ([here's the one for Inky Frame](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/inky_frame), for example).

**Comment by FrancescoSaverioZuppichini** [comment]
Oh thanks a lot! :) I have a pico enviro+, got it to work!
