### ISSUE TITLE
Rotate Orientation

### ISSUE THREAD

**Issue by Lumb3rJaX** [pimoroni/pimoroni-pico#518]
I have a lanyard that I like to wear for events/cons but it is a portrait orientation as opposed to a landscape one. is there a way to setup the OS/program so that it is displayed fully rotated? I haven't been able to find documentation that mentions this so I thought I'd ask here.

**Comment by Gadgetoid** [comment]
Which display are you using?

**Comment by helgibbons** [comment]
Closing this for now, but feel free to re-open if needed.
