### ISSUE TITLE
Pico Explorer backlight setting (MicroPython)

### ISSUE THREAD

**Issue by evilbobbins** [pimoroni/pimoroni-pico#53]
On the Pico Explorer using MicroPython the explorer.set_backlight(X.X) command is being ignored and always defaults to 1.0 IE full brightness
I tested on Alpha 0.04, 0.05 and 0.06 with the same result

**Comment by ZodiusInfuser** [comment]
Apologies, but the PicoExplorer does not have a controllable backlight, see the pinout diagram below.
![image](https://user-images.githubusercontent.com/7437269/107662788-8eaa3600-6c82-11eb-808d-bbd34acba044.png)
We will remove those functions in the near future.

**Comment by Gadgetoid** [comment]
Removed in v0.0.7 - https://github.com/pimoroni/pimoroni-pico/releases/tag/v0.0.7
