### ISSUE TITLE
Builds that have ulab preinstalled

### ISSUE THREAD

**Issue by Darkai87** [pimoroni/pimoroni-pico#551]
Which of the 12 builds could I download that have the ulab library already built in? Just curious because I can't see any information on which builds have it and which don't for the raspberry pi pico. Thanks.

**Comment by helgibbons** [comment]
Hello! It's currently the builds for boards that have extra flash memory that include `ulab` - that's the Pimoroni Pico LiPo builds and Tiny 2040 8MB.

(`ulab` is a chunky module and I believe it was making the file sizes unworkably large for 2MB boards!)

**Comment by yezzer** [comment]
@Darkai87 if it's of interested, i've loosely-documented [how to compile new Pico firmware with ulab numpy included](https://medium.com/@iestynlloyd/galactic-unicorns-and-custom-pimoroni-pico-firmware-38dd7c5913b8)

**Comment by Darkai87** [comment]
@yezzer would you be able to send me your copy of your uf2 file with ulab numpy included? I'm struggling to compile this pico firmware with your instructions because I'm not the most github inclined.

**Comment by yezzerfv** [comment]
> [Darkai87](/Darkai87)

DM me on twitter - same username

**Comment by yezzer** [comment]
@Darkai87 dm me on twitter - same username

**Comment by Gadgetoid** [comment]
I've added a note to the latest release to clarify that ulab is available in: Cosmic Unicorn, Galactic Unicorn, Stellar Unicorn, Tufty 2040, Pico LiPo 4MB and Pico LiPo 16MB.

Basically anything with > 2MB flash *or* a product I can get away with pruning some other libraries from (Cosmic, Galactic and Stellar are carefully pruned to fit ulab).
