### ISSUE TITLE
Pico Display rotated 180 degree y axis is off by 1

### ISSUE THREAD

**Issue by rtitmuss** [pimoroni/pimoroni-pico#562]
When the Pico Display is used with 180 degree rotation the y axis is off by one pixel. The top row is inaccessible, on power on it displays random values, or the previous row if you've configured the display with 0 degree rotation. The bottom row is not displayed.

The following test demonstrates the issue. The expected behaviour is:
1.  black screen
2. green box
3. black screen
4. red box

Actual behaviour is:
1. on boot top row shows random values, or later iterations red line
2. top row shows the previous value, green line on second row and the bottom row is missing
3. black screen
4. red box

https://user-images.githubusercontent.com/890714/200114947-af240d25-cf64-4abf-b382-3045c926371f.mp4

```
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_P4
import time

MIN_X = 0
MAX_X = 239       
MIN_Y = 0
MAX_Y = 134

def draw_outline(rotate):
    display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, pen_type=PEN_P4, rotate=rotate)

    RED = display.create_pen(255, 0, 0)
    GREEN = display.create_pen(0, 255, 0)
    BLACK = display.create_pen(0, 0, 0)

    display.set_pen(BLACK)
    display.clear()
    display.update()

    time.sleep(1)

    display.set_pen(RED if rotate == 0 else GREEN)
    display.line(MIN_X, MIN_Y, MAX_X, MIN_Y)
    display.line(MAX_X, MIN_Y, MAX_X, MAX_Y)
    display.line(MAX_X, MAX_Y, MIN_X, MAX_Y)
    display.line(MIN_X, MAX_Y, MIN_X, MIN_Y)
    display.update()

while True:
    draw_outline(180)
    time.sleep(1)
    
    draw_outline(0)
    time.sleep(1)
```

**Comment by Gadgetoid** [comment]
Took an embarrassingly long time to look into this, but I think I've got a fix - https://github.com/pimoroni/pimoroni-pico/pull/912

I can't fathom why it needs a little 1px nudge on these rotations but I suspect it has something to do with the scan order and inclusive vs exclusive ranges.
