### ISSUE TITLE
Typo in reactive_encoder.py

### ISSUE THREAD

**Issue by pkingpi** [pimoroni/pimoroni-pico#564]
There's a typo in the code for this MicroPython example for the Inventor 2040 W. It should say 'motor_gear_ratio', not 'motor_rear_ratio'.

**Comment by helgibbons** [comment]
Fixed this in #568 :)

**Comment by sharmadhiraj86** [comment]
@helgibbons please let me fix this and raise a PR. I have my 30% component of one entire subject for the open source contribution. I will get that 30% only if my PR gets merged.
