### ISSUE TITLE
Galactic Unicorn won't display JPGs correctly

### ISSUE THREAD

**Issue by yezzer** [pimoroni/pimoroni-pico#573]
I have partially fixed this, following @Gadgetoid's pointers.

Using the included jpegdec, an image would load in and display incorrectly:
**Incorrect**
![image](https://user-images.githubusercontent.com/1615954/201495358-27fcce97-472a-4d3d-aff6-5a170ce29c10.png)
**Correct** (Note: 8x8 pixels)
![grad-ps-3](https://user-images.githubusercontent.com/1615954/201495390-b8226796-ec94-494d-a7da-395ba6ab227e.jpg)

Editing jpegdec.cpp and adding the following in `int JPEGDraw(JPEGDRAW *pDraw)` resulted in the colours displaying correctly
```
else if(pDraw->iBpp == 16) {
        for(int y = 0; y < pDraw->iHeight; y++) {
            for(int x = 0; x < pDraw->iWidth; x++) {
                int i = y * pDraw->iWidth + x;
                current_graphics->set_pen(RGB(pDraw->pPixels[i]).to_rgb888());
                current_graphics->pixel({pDraw->x + x, pDraw->y + y});   
            }   
        }
```
**Fixed colours**
![image](https://user-images.githubusercontent.com/1615954/201495509-0e919651-785d-4028-a241-2c1b7c9816b7.png)

However, the last few columns of the image repeats.
This is not true of all sizes:
![image](https://user-images.githubusercontent.com/1615954/201495536-7b135370-3f71-42a3-87e5-9485ab6bb04d.png)

I don't do C++, so am a bit lost now. I've been able to figure out that `pDraw->iWidth` in `int JPEGDraw(JPEGDRAW *pDraw)` is incorrect though.

If anyone can make any suggestions, I can continue to try, but feel i'm unable to progress now. :)

**Comment by Gadgetoid** [comment]
The auto builds here should at least now have the right pixel type - https://github.com/pimoroni/pimoroni-pico/pull/600

But I'm not sure what's going on with the width. Looks like your 11x11 pixel example is going wrong?

**Comment by yezzer** [comment]
> The auto builds here should at least now have the right pixel type - #600
> 
> But I'm not sure what's going on with the width. Looks like your 11x11 pixel example is going wrong?

Yeah, some width JPGs have additional columns/rows. I haven't looked into it further as I paused dev on this project.

**Comment by Gadgetoid** [comment]
I've synced JPEGDEC with the latest upstream changes to see if that's the cause, I'll have a poke.

Don't happen to have your 11x11 jpeg handy, do you?
