### ISSUE TITLE
README.md for Pico Graphics doesn't mention ascii tables

### ISSUE THREAD

**Issue by katch33** [pimoroni/pimoroni-pico#580]
The documentation explaining how to print individual characters to the screen doesn't mention that you use the numerical ascii references to choose what to print. It may be obvious to a lot of people but as a beginner with python and hardware it wasn't clear to me at all. I found the deprecated repo by googling the function itself and that's where I came across the info.

I suggest adding a line explaining that users will need to look up an ascii table to figure out which character to print.

**Comment by helgibbons** [comment]
I expanded on the description of `display.character()` a bit in #592 :)
