### ISSUE TITLE
Graph plotted up-side-down ?

### ISSUE THREAD

**Issue by tonygo** [pimoroni/pimoroni-pico#583]
As angle increases from -360 degrees and 0 degrees sine(angle) should rise. Here it goes negative.

Line 29 : 
y = int((sin(radians(angle + offset)) * 24) + 32)

should possibly be: 
y = int(32 - (sin(radians(angle + offset)) * 24) ) ??

**Comment by helgibbons** [comment]
Fixed in #585 !
