### ISSUE TITLE
Suggestion: pico_display API

### ISSUE THREAD

**Issue by sumitkm** [pimoroni/pimoroni-pico#59]
Since the display needs a call to `init()` to be usable, can we consider setting `set_pen(0,0,0)` and calling `clear()`, internally, the first time `init` is called?

Not really a big deal. 

I am trying to figure out what it takes to make a pull request, but a complete n00b at Micropython build environment. Still trying to wrap my head around how to test my changes :-)

**Comment by Pinkyatacme** [comment]
Personally, I would suggest that a overloaded call to init, with RGB values for the background would be preferable. If you look at the display demo code, that uses a rather nasty brownish colour for the background, so a black background, while likely to be the most common, is certainly not an automatic choice in all cases.

**Comment by helgibbons** [comment]
Closing as relates to old pico_display API.

New shininess here!: https://github.com/pimoroni/pimoroni-pico/blob/main/libraries/pico_graphics/README.md
