### ISSUE TITLE
Pi Pico W fails to connect to open Wifi network

### ISSUE THREAD

**Issue by loicbr** [pimoroni/pimoroni-pico#590]
When trying to connect to an open network (auth type 0), the following reply is returned:

```
wlan.connect(ssid)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
OSError: [Errno 1] EPERM
```
same with : 
`wlan.connect(ssid, security=0)`

See https://github.com/micropython/micropython/issues/9016

Using https://github.com/gwo0d/cyw43-driver/tree/AUTH_OPEN_fix as `lib/cyw43-driver` submodule does fix it.

**Comment by Gadgetoid** [comment]
Thanks for the heads up, but I can't include downstream fixes in our MicroPython builds. Will have to wait for https://github.com/georgerobotics/cyw43-driver/pull/45 to be approved & merged and the lib submodule updated.
