### ISSUE TITLE
[Badger 2040] include halt() in documentation?

### ISSUE THREAD

**Issue by bucketfish** [pimoroni/pimoroni-pico#594]
while looking through some github repos of badger code, i came across the function `halt()`, which doesn't seem to be in the documentation. perhaps it should be, in somewhere like the [updating the display](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/modules/badger2040#updating-the-display) section? hopefully there isn't a reason for it to not be there that i've missed :'

thanks!

**Comment by Gadgetoid** [comment]
Badger 2040 and Badger 2040 W now live here: https://github.com/pimoroni/badger2040/

I don't think we have covered this in the docs, so I'm going to close the issue here but make a note to check.
