### ISSUE TITLE
Pico Graphics enhancements

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/pimoroni-pico#6]
* [ ] `h_span` and `v_span` for fast horizontal/vertical lines
* [x] maybe make `create_pen` constexpr, so the bit twiddling can be evaluated at compile time? - https://en.cppreference.com/w/cpp/language/constant_expression
* [x] `set_clip` should use `clip = r.intersection(bounds);` to avoid setting a clip region larger than the buffer
* [x] `typedef uint16_t pen` and use `pen` in lieu of `uint16_t` when handling pens? feels cleaner and permits code to be portable to a hypothetical future library where `pen` is of another type.

**Comment by lowfatcode** [comment]
> * `h_span` and `v_span` for fast horizontal/vertical lines

We wil add a more friendly `line(start, end)` method which has special cases for vertical/horizontal. The existing `pixel_span` function is really intended for internal use by other primitive drawing methods and I will be removing clipping from that method for performance reasons shortly.
