### ISSUE TITLE
badger2040 partial update affects parts of screen outside update region

### ISSUE THREAD

**Issue by joonoro** [pimoroni/pimoroni-pico#604]
Run the following example code.

Expected behavior: only the updated region changes, rest of the screen should be unchanged
Actual behavior: updated region updates, but rest of the screen fades out

```py
import badger2040

badger = badger2040.Badger2040()

badger.pen(15)
badger.clear()

badger.pen(0)
badger.rectangle(5, 5, 50, 50)
badger.rectangle(5, 50, 80, 50)
badger.rectangle(5, 100, 100, 50)
badger.update()

badger.update_speed(badger2040.UPDATE_TURBO)

for i in range(30):
    badger.pen(0)
    badger.rectangle(210, 0, 60, 128)
    badger.partial_update(210, 0, 60, 128)

badger.halt()


```

**Comment by Gadgetoid** [comment]
Badger 2040 and Badger 2040 W now live here: https://github.com/pimoroni/badger2040/

Unfortunately partial update affecting the rest of the screen is just (afaik) par for the source with e-ink. I don't think we can fix this. You need to do periodic full refreshes to keep the contrast.

Closing this issue to keep Badger 2040 to its new home. Please feel free to re-open over at https://github.com/pimoroni/badger2040/issues with a link back here for posterity.
