### ISSUE TITLE
Can this be imported into the arduino IDE?

### ISSUE THREAD

**Issue by SutliffeProductions** [pimoroni/pimoroni-pico#611]
I'm probably being super dumb. I'm trying to use the Display Pack, and i want to use it with the Arduino ide, is importing the correct libraries possible? if so, how? as there isn't any clear documentation.

**Comment by helgibbons** [comment]
I don't think we've had a chance to try Pico with Arduino IDE yet - maybe someone more knowledgeable in this area can help?

**Comment by ZodiusInfuser** [comment]
Hi @SutliffeProductions. The display pack uses an ST7789 LCD driver, which is pretty common. As such there are numerous guides out there for controlling it, including via Arduino. Here's one that may work for you: https://simple-circuit.com/arduino-st7789-ips-tft-display-example/

Here is the pinout for the display pack, which should help you set the appropriate pins to use the pack
![image](https://user-images.githubusercontent.com/7437269/213792712-4bb5df0b-3955-43a9-994a-910bba25f797.png)
