### ISSUE TITLE
Example offered - PicoGraphics colour implementation of zoomable Mandelbrot set display

### ISSUE THREAD

**Issue by ExperiMentor** [pimoroni/pimoroni-pico#619]
This full colour adaptation for PicoGraphics of a zoomable Mandelbrot set display makes excellent use of Pico Explorer Base (display, 4 buttons, 3x ADC with 3x potentiometers mounted on the breadboard. The programming uses simultaneous dual-threads for speed

Please feel free to include it in your examples if desired!

https://github.com/ExperiMentor/PicoGraphics_Zoomable_Mandelbrot

**Comment by helgibbons** [comment]
I'll add a link to your project in the Pico Explorer readme, thank you :)
