### ISSUE TITLE
Interstate 75 w Pico example for Wii Nunchuk

### ISSUE THREAD

**Issue by antiero** [pimoroni/pimoroni-pico#635]
I'm trying to connect an [Adafruit Wii Nunchuck Breakout Adapter](https://shop.pimoroni.com/products/adafruit-wii-nunchuck-breakout-adapter-qwiic-stemma-qt?variant=32348080963667) to the [Interstate 75 W board](https://shop.pimoroni.com/products/interstate-75-w?variant=40453881299027) 's QW/ST port, but really struggling to find any docs or examples for this.. I'd ideally like a MicroPython or CircuitPython example if possible - any help much appreciated!

![pico_nunchuk](https://user-images.githubusercontent.com/4693265/212546310-fa20a2c4-bd33-4d1f-bab2-e43bb8d191c8.jpg)

**Comment by ZodiusInfuser** [comment]
Hi, perhaps you have come cross this already, but here is some Micropython code I found that could work: https://github.com/kfricke/micropython-nunchuck

Here is the Circuitpython code for that adafruit Nunchuk adapter, which could be useful for converting to Micropython: https://github.com/adafruit/Adafruit_CircuitPython_Nunchuk/blob/main/adafruit_nunchuk.py

**Comment by antiero** [comment]
Thanks @ZodiusInfuser , I got this working in the end! Will tidy up the code and share an example soon.

**Comment by ZodiusInfuser** [comment]
That's great to hear, and see! Thanks for sharing
