### ISSUE TITLE
Interstate 75 - Interacting with BOOT button using interstate.py

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/pimoroni-pico#654]
Interstate 75 W has 'A' and 'B' buttons, Interstate 75 has 'A' 'and 'BOOT' buttons.

There's currently no way of reading the BOOT button on Interstate 75 (non W) using interstate.py - can we add this?

**Comment by ageeandakeyboard** [comment]
Pull request made that fixes this issue. hopefully will be included in next release.

**Comment by ZodiusInfuser** [comment]
Yea, about that... 😅

**Comment by ageeandakeyboard** [comment]
All fixed and checked against i75 and i75w
