### ISSUE TITLE
Galactic Unicorn micropython feature_test_with_audio.py checks wrong button states.

### ISSUE THREAD

**Issue by colin-grant** [pimoroni/pimoroni-pico#661]
In the example `feature_test_with_audio.py` script, when checking for the 'D' button or the 'ZZZ' button presses, the example code is checking the wrong button state. 

i.e. 
```   
if gu.is_pressed(GalacticUnicorn.SWITCH_D):
        if not was_c_pressed:
```
and 
```    
if gu.is_pressed(GalacticUnicorn.SWITCH_SLEEP):
        if not was_d_pressed:
```

This could cause the switch presses to be detected multiple times if the switches are held.

**Comment by ZodiusInfuser** [comment]
Thanks for raising this! I think that was my mistake with some copy and pasting at the last minute 😅
