### ISSUE TITLE
Pico Display Pack - pinout wrong

### ISSUE THREAD

**Issue by phedoff** [pimoroni/pimoroni-pico#67]
The pinout on the [product page](https://shop.pimoroni.com/products/pico-display-pack) graphic is wrong. 
The correct pins are 

- led_r: 9 (GP6)
- led_g: 10 (GP7)
- led_b: 11 (GP8)

Discovered it the hard way, could have looked in the code [here](https://github.com/pimoroni/pimoroni-pico/blob/main/libraries/pico_display/pico_display.cpp). D'oh!

**Comment by helgibbons** [comment]
Oops, out by one! Sorry about that, we'll get the graphic updated.

**Comment by phedoff** [comment]
No problem. Can you close this issue when it's corrected or do I have to do it?

**Comment by helgibbons** [comment]
No worries, I'll close it when it's sorted - it's usefully visible until then :)

**Comment by helgibbons** [comment]
All sorted 👍
