### ISSUE TITLE
Strings containing '\n' are never broken onto multiple lines by bitmap_fonts.cpp

### ISSUE THREAD

**Issue by paul-bivol** [pimoroni/pimoroni-pico#684]
Try to use bitmap::text() to print a string with a newline (like "foo\nbar"). It is printed on the same line instead of being broken onto 2 different lines.

**Comment by helgibbons** [comment]
Hopefully \n should be working properly with [v1.20.4](https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.20.4)!

**Comment by paul-bivol** [comment]
Looks like eee28a6f942fa4a4432cf3f26afbd51c21a147df might address the issue. Will re-test soon.

**Comment by paul-bivol** [comment]
Works fine.
