### ISSUE TITLE
Localhost / 127.0.0.1 on the Badger2040w

### ISSUE THREAD

**Issue by North101** [pimoroni/pimoroni-pico#689]
Does localhost / 127.0.0.1 work on the picow?

I can run my server code on one picow and have another picow connect to it, but running the same server code in a thread and trying to connect to localhost / 127.0.0.1 doesn't work

`socket.getaddrinfo('localhost', 1246)` hangs
`socket.connect(('127.0.0.1', 1246))` errors with `EHOSTUNREACH`

If i run the code on my mac's micropython it works

Is there anything I'm missing?

**Comment by Gadgetoid** [comment]
I would imagine not, the Pico isn't really meaningfully capable of running multiple simultaneous processes so even if there was local loopback support your request would block your response and vice versa.

What are you trying to accomplish?

**Comment by North101** [comment]
Ok, that makes sense. I have 4 pico w's all talking to each other over wifi and one of them was going to act as a server and client, while the other were clients. For simplicity sake, I was hoping to reuse the client code and just connect to localhost

**Comment by Gadgetoid** [comment]
Ah, I getcha. Should be able to abstract the core of the server/client enough that they can just use a direct function call for inter-process communication.
