### ISSUE TITLE
Badger 2040W visual banding appearing after power down

### ISSUE THREAD

**Issue by itadams** [pimoroni/pimoroni-pico#704]
https://user-images.githubusercontent.com/118774853/222847265-c8eb8a71-9fab-499d-b563-790b732ee323.mp4

I'm seeing banding appearing on the Badger 2040W using the reference software when it powers off (powered by battery or when the usb power is removed).

It's a gradual effect and my initial guess would be some form of capacitance discharge but that's just me guessing.

Does anybody with any better knowledge of the display know if this is a known issue or something that the software driver for the display can affect?

**Comment by Zoobdude** [comment]
I had this issue when my badger first arrived. Updated to the newest release and it was solved. Have you updated?
