### ISSUE TITLE
Badger 2040 w and RTC

### ISSUE THREAD

**Issue by stayfrosty00** [pimoroni/pimoroni-pico#710]
The documentation says there is a way to wake the Badger using the RTC but it does not seem to be implemented in badger2040w.py like it is with the inky frame.

**Comment by Gadgetoid** [comment]
Dupe of https://github.com/pimoroni/badger2040/issues/4

I'm working on porting the basic RTC management functions I wrote for Inky Frame.

**Comment by stayfrosty00** [comment]
Thank you for your hard work!
