### ISSUE TITLE
Buttons not available on Pico Unicorn 1.19.17

### ISSUE THREAD

**Issue by NHurst99** [pimoroni/pimoroni-pico#724]
Pico Unicorn Pack does not have any button variables in 1.19.17
![image](https://user-images.githubusercontent.com/25715845/227127500-f016196c-0175-4146-a21b-7df0fb757f13.png)
If it still is available, the unicorn examples should be updated, as the example code is what I used.

Buttons were working in 1.19.16:
![image](https://user-images.githubusercontent.com/25715845/227128114-7e357ce4-a5c4-45b4-9cc8-4efa8017822a.png)

**Comment by Gadgetoid** [comment]
The button constants are on the module, rather than the class instance.

Example code needs to reflect this!

**Comment by Gadgetoid** [comment]
Added a commit onto https://github.com/pimoroni/pimoroni-pico/pull/733 to change the module, rather than the examples. Should be in the next release!
