### ISSUE TITLE
Ghosting on Cosmic Unicorn

### ISSUE THREAD

**Issue by Leone25** [pimoroni/pimoroni-pico#741]
Hello,

while working on a project on my Cosmic Unicorn I noticed that there is a ghost image shifted down one line of what is displayed on the screen, plus the last line is "ghosted" in the middle of the screen.
I've already contacted support about this and they were able to reproduce the issue as well so it seems like it's a firmware issue.
Here is a picture of what it looks like with [this code](https://pastebin.com/wWpyMRHf) code running (taken in a dim room with phone in night mode): 
![P_20230325_184608](https://user-images.githubusercontent.com/39310565/229146476-f97e38c2-fdf2-4f25-b432-ff7a8d01fb59.jpg)

This seems an issue very similar to #666 .

I hope it's possible to fix.

Thanks in advance

Enrico

**Comment by Gadgetoid** [comment]
@MichaelBell figured it out for Galactic and the same solution should be portable, as far as I'm aware. It was on my TODO list, but I haven't wrapped my brain around the code yet.

**Comment by Leone25** [comment]
great, will wait for a fix
thx

**Comment by MichaelBell** [comment]
Possible fix on this branch: https://github.com/MichaelBell/pimoroni-pico/tree/cosmic-ghost-fix
This was just applying the same thing I did on galactic, but I'm away from home so haven't tested it - can do that in a couple of weeks!

**Comment by MichaelBell** [comment]
I've had a chance to test this now - looks like that fix does work so I've submitted a PR.
