### ISSUE TITLE
New micorpython v1.20 release not working with Cosmic Unicorn

### ISSUE THREAD

**Issue by janpacak-wilhelmsen** [pimoroni/pimoroni-pico#763]
Copying `pimoroni-cosmic_unicorn-v1.20.0-micropython.uf2` to Pico isn't resulting in having available serial port after Pico reboot.

Both `pimoroni-picow_cosmic_unicorn-v1.19.16-micropython.uf2` and `rp2-pico-w-20230427-unstable-v1.20.0-24-g867e4dd3d.uf2` firmwares are having serial port after restart available on the same Pico W.

Don't know, howto debug more. Tried `pimoroni-galactic_unicorn-v1.20.0-micropython.uf2`, but seems to have the same issue.

**Comment by Gadgetoid** [comment]
Have the same problem here.

Stumped by this, it was supposed to be a straight-forward release but something has gone very wrong!

**Comment by Gadgetoid** [comment]
This release should work! https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.20.1
