### ISSUE TITLE
Build all fails due to error (main, 302d6ae)

### ISSUE THREAD

**Issue by hptechdesign** [pimoroni/pimoroni-pico#769]
Building all from latest main (302d6ae), I got an error at line 220 of pimoroni-pico\drivers\vl53l1x\vl53l1x.cpp:

error: '__bswap32' was not declared in this scope

Looking at the commit history, line 220 got missed when commit  21b4ff6 was made on Feb 10th. 

I solved by changing line 220 of vl531x.cpp from
`  return __bswap16(value);`
to 
`  return __builtin_bswap16(value);`

**Comment by raybellis** [comment]
This and a couple other issues is resolved in my #771
