### ISSUE TITLE
Accessing VBUS / 5V on Inventor 2040W

### ISSUE THREAD

**Issue by SebastianChristoph** [pimoroni/pimoroni-pico#819]
Hello,
is there any way to access the VBUS-Pin on the Inventor2040W ?
While using just the PICO, I can access the VBUS Pin to get the 5V Power from the USB.
Is there any chance that this is possible with the Inventor2040W ?

Thank you!

**Comment by ZodiusInfuser** [comment]
Hi @SebastianChristoph

The best way to get 5V out of the Inventor 2040W is to use one of the power pins from the Servo headers. This will receive power from either USB or the battery connector (whichever is higher).

If you are specifically needing VBUS then the only way to access that is by soldering on top of the Pico W's pad for that pin.

Hope that helps
