### ISSUE TITLE
Where are the fonts

### ISSUE THREAD

**Issue by mohir** [pimoroni/pimoroni-pico#824]
Hello,
In the clock.py example, of the Stellar Unicorn it is written:
"This example uses a custom tiny bitmap font, find 3x5.bitmapfont in [fonts](https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/common/fonts) and copy it to your Pico W."
But the link brings a page not found error.

**Comment by helgibbons** [comment]
It's in `common/fonts` - try here:

https://github.com/pimoroni/pimoroni-pico/tree/main/common/fonts
