### ISSUE TITLE
Machine PWM duty_u16 Inverted

### ISSUE THREAD

**Issue by A-Krau** [pimoroni/pimoroni-pico#84]
Compared to "stock" MicroPython UF2 and built in libraries the duty_u16 appears to be inverted in Pimoroni Port. 

Below example yields led full on in MicroPython and full off in Pimoroni's Port.
```
from machine import Pin
from machine import PWM

led = PWM(Pin(25, Pin.OUT))
led.freq(1000)
led.duty_u16(65535)
```

**Comment by Gadgetoid** [comment]
This has presumably been fixed in a more recent release since we've now got the support we need upstreamed to build against mainline.
