### ISSUE TITLE
Incorrect documentation for Pico Scroll

### ISSUE THREAD

**Issue by DunbarChas** [pimoroni/pimoroni-pico#861]
In the https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/modules/pico_scroll It shows using the update method to display new content to the screen however in the micropython it should be show()

**Comment by Battleroid** [comment]
The demos don't seem to work with `show()` instead of `update()` either.

**Comment by helgibbons** [comment]
Looks like the docs never got updated when we rejigged things to make Scroll Pack work with PicoGraphics - I've attempted to improve things a little with #876 :)
