### ISSUE TITLE
picographics - fixed_width parameter missing from method text()

### ISSUE THREAD

**Issue by swm11** [pimoroni/pimoroni-pico#908]
The readme for picographics provides the following signature:
```
display.text(text, x, y, wordwrap, scale, angle, spacing)
```

The text after that also describes the fixed_width parameter:
```
fixed_width - space all characters equal distance apart (monospace)
```

However, as far as I can determine, this hasn't been implemented but it would be useful.  I'm testing on a Badger 2040 W  (wonderful device!!!).

**Comment by Gadgetoid** [comment]
I think the `fixed_width` argument is implemented, if you supply the keyword argument `fixed_width=True` to `display.text()` it should work.

There were some fixes to it for Badger - https://github.com/pimoroni/badger2040/issues/51

**Comment by swm11** [comment]
Thanks for the feedback.  My mistake - I was using an out-of-date distribution on my Badger-W.

In the PicoGraphics README.md you might like to change:
```
display.text(text, x, y, wordwrap, scale, angle, spacing)
```
to
```
display.text(text, x, y, wordwrap, scale, angle, spacing, fixed_width)
```

**Comment by swm11** [comment]
Thanks for the feedback. My mistake - I was using an out-of-date distribution on my Badger-W.

In the PicoGraphics README.md you might like to change:
```
display.text(text, x, y, wordwrap, scale, angle, spacing)
```
to
```
display.text(text, x, y, wordwrap, scale, angle, spacing, fixed_width)
```
