### ISSUE TITLE
pico_explorer documention

### ISSUE THREAD

**Issue by citizenfish** [pimoroni/pimoroni-pico#92]
Is this documentation correct [libraries/pico_explorer](https://github.com/pimoroni/pimoroni-pico/tree/main/libraries/pico_explorer)

As it looks to me like the methods:-

- set_backlight()
- set_adc()

Are not implemented in pico_explorer

**Comment by Gadgetoid** [comment]
Has `get_adc()` but `set_backlight()` was removed because there's no manual backlight control on Pico Explorer. Looks like it's still in the index, so I'll fix that ASAP. Thanks.
