### ISSUE TITLE
Pico Explorer Base schematic RUN pin?

### ISSUE THREAD

**Issue by bgolab** [pimoroni/pimoroni-pico#95]
Just got the board. 

It looks like the RUN pin is NOT available through any connector?

I do not have access to the schematic. Am I right? Any idea how to access the RUN pin?

**Comment by ZodiusInfuser** [comment]
Hi. Yes, you are correct that the run pin is not wired to a header on the Pico Explorer. The way around this would either get one of our pico reset switches:
- https://shop.pimoroni.com/products/captain-resetti-pico-reset-button

or get a PicoProto board and some headers and solder on a button on a wire:
- https://shop.pimoroni.com/products/pico-proto
- https://shop.pimoroni.com/products/esp32-thing-stackable-header-set

Here's my attempt at the latter: https://twitter.com/ZodiusInfuser/status/1358114439065665537?s=20
