### ISSUE TITLE
Running 75W/Placekitten.py fails

### ISSUE THREAD

**Issue by ajyuan** [pimoroni/pimoroni-pico#958]
Placekitten.py fails because of the following error:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ImportError: no module named 'urllib'

This is with driver [picow-v1.23.0-1-pimoroni-micropython.uf2](https://github.com/pimoroni/pimoroni-pico/releases/download/v1.23.0-1/picow-v1.23.0-1-pimoroni-micropython.uf2).

Not sure how I can install urllib into my Pico? All other examples work using urequests.

**Comment by helgibbons** [comment]
You should be able to install urllib.urequest through Thonny's 'Manage Packages':
![image](https://github.com/pimoroni/pimoroni-pico/assets/50950368/4fb98925-a634-4e8f-85b0-552bad513b83)

Or there's a compiled version here that you can copy to the lib folder on your Pico W: https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/common

**Comment by ajyuan** [comment]
Thanks!
