### ISSUE TITLE
pico-sdk 2 - Not all things build anymore.

### ISSUE THREAD

**Issue by AndrewCapon** [pimoroni/pimoroni-pico#981]
This is easy to replicate.

1. Get the latest pico-sdk
2. Get the latest from here
3. Try to build all

I'm guessing this is to do with recent changes to pico-sdk?

**Comment by Gadgetoid** [comment]
Yup already a PR open - https://github.com/pimoroni/pimoroni-pico/pull/980

**Comment by AndrewCapon** [comment]
Ah, Good stuff.

I spent quite a while thinking it was my merge from main into my branch (and the fact git hates me) causing the problems :)
